In [1]:
import numpy as np


In [2]:
a=np.array([1,2,3,4])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
b=np.array([[5,6],[7,8],[9,10]])

In [5]:
b

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [6]:
print(a.shape,b.shape)

(4,) (3, 2)


In [7]:
c=a.reshape((4,1))

In [12]:
c.shape

(4, 1)

In [13]:
d=a.reshape((2,-1,1))

In [14]:
d.shape

(2, 2, 1)

In [15]:
a=np.array([1,2,3])
b=np.array([4,5])

In [16]:
c=np.concatenate((a,b))

In [17]:
c

array([1, 2, 3, 4, 5])

In [18]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [19]:
c=a+b
c

array([5, 7, 9])

In [21]:
c=np.array([[10]])
d=a+c
d

array([[11, 12, 13]])

In [22]:
e=a+5
e

array([6, 7, 8])

In [24]:
a=np.array([1,2,3,4,5,6,7])
b=a[3:6]
b

array([4, 5, 6])

In [29]:
b=a[2:7:3]
b


array([3, 6])

In [30]:
c=a[a>4]
c

array([5, 6, 7])

In [31]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [32]:
sum_a=np.sum(a)
sum_a

np.int64(28)

In [35]:
a=np.array([2,6,0,56,89,72,198])
s=np.sort(a)
s

array([  0,   2,   6,  56,  72,  89, 198])

In [33]:
max_a=np.max(a)
max(a)

np.int64(7)

In [34]:
min_a=np.min(a)
min(a)

np.int64(1)

In [36]:
a=np.random.randint(0,10,(3,4))
a

array([[2, 0, 7, 3],
       [9, 3, 2, 9],
       [1, 1, 9, 4]], dtype=int32)

In [37]:
a=np.array([4,6,8])
b=np.array([1,2,3])
c=np.vstack((a,b))
c

array([[4, 6, 8],
       [1, 2, 3]])

In [39]:
c=np.hstack((a,b))
c


array([4, 6, 8, 1, 2, 3])

In [40]:
c.shape

(6,)

In [41]:
a

array([4, 6, 8])

In [44]:
mean_a=np.mean(a)
mean_a

np.float64(6.0)

In [45]:
std_a=np.std(a)
std_a

np.float64(1.632993161855452)

In [46]:
norm_a=(a-mean_a)/std_a
norm_a

array([-1.22474487,  0.        ,  1.22474487])

In [47]:
np.mean(norm_a)

np.float64(0.0)

In [49]:
np.std(norm_a)

np.float64(0.9999999999999999)